version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "🔀"
    labels: ["github-actions"]
    target-branch: "dev"
    reviewers:
      - "Jarmos-san"

  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
      time: "06:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "🔀"
    labels: ["submodule"]
    target-branch: "dev"
    ignore:
      - dependency-name: "docs/blog.wiki"
    reviewers:
      - "Jarmos-san"
